---
name: ci
on: push

jobs:
  node:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: just test
